{% set name = "agox" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/agox-{{ version }}.tar.gz
  sha256: 887a940876bd8354fdfb5f90d7b8766282a063086c7edca4c1de5927e154534c

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - cymem
    - numpy
    - pip
  run:
    - ase
    - python
    - cymem
    - h5py
    - matscipy
    - scikit-learn
    - numpy <1.24
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - agox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://agox.gitlab.io/agox/
  summary: Atomistic Global Optimziation X is a framework for structure optimization in materials science.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
